version: "3.9"

services:
  cms:
    container_name: cms
    build:
      context: ../cms
      args:
        COMMIT_HASH: 4ccf84a68d9328e45af9ea473ca62c192b3e1326
    depends_on:
      - mariadb
    ports:
      - "8080:80"
