version: "3.9"

services:
  cms:
    container_name: cms
    build:
      context: ../cms
      args:
        COMMIT_HASH: e07f295ffc38c33a2bc71e0481857928c67caa56
    depends_on:
      - mariadb
    ports:
      - "8080:80"
