version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.22
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=cNGjxeuLrEG3tHWh
      - MARIADB_DATABASE=cms
      - MARIADB_USER=ie105
      - MARIADB_PASSWORD=r8cU4V6mBSFFMXCq
